spring.application.name=eurake-server
server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Permite que las instancias que no mandan heartbeat sean eliminadas.
eureka.server.enable-self-preservation=false 
