spring.application.name=producto-service
server.port=8082

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://postgres:5432/productos_db
spring.datasource.username=postgres
spring.datasource.password=28demarzo
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate con PostgreSQL
spring.jpa.database=POSTGRESQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Eureka Client
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true

# SpringDoc OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
